name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Code download karo
      uses: actions/checkout@v3
    
    - name: Java 17 setup karo
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Compile karo
      run: javac HelloRover.java
    
    - name: Run karo
      run: java HelloRover
